### ISSUE TITLE
Readme example leaves out most important part: slots

### ISSUE THREAD

**Issue by redbar0n** [koordinates/xstate-tree#28]
Readme says slots is the defining feature of xstate-tree:

>Actors views are composed together via "slots", which can be rendered in the view to provide child actors a place to render their views in the parent's view.

But it leaves it out of the example, so it's hard to see how slots would look and feel when using xstate-tree to its full extent:

```
// If this tree had more than a single machine the slots to render child machines into would be defined here
const slots = [];
```

**Comment by redbar0n** [comment]
The codesandbox example still only has one single child slot. It would be helpful if it had at least 2 or 3, to get an idea of how it scales.

**Comment by redbar0n** [comment]
In the codesandbox: The slots are also passed into the view, but they don’t seem to be used there..

**Comment by UberMouse** [comment]
The slot is used here in the view https://codesandbox.io/s/xstate-tree-b0el6e-forked-4i6txh?file=/src/index.tsx:3304-3328

Feel free to expand the example with more slots :) there is no real difference between 1 and 3 slots except you have 3 slots defined and 3 slots rendered in the view.
